# -*- coding: utf-8 -*-
"""
apply_v5_polish.py — 英文 v5 人味化润色（用户批准，中文版暂不同步）。
只改 10 段：AI 腔套话/元话语/节奏，不动任何数字、引用 [n]、图表号、技术声明。
每段整段替换前断言原文逐字符匹配；替换后做"含数字 token 多重集 + Fig/Table/Section 引用"
零漂移校验。产物：paper/polish-v5-diff.md（逐段对照清单，供用户过目）。
"""
import re
import shutil
from collections import Counter
from pathlib import Path
from docx import Document

ROOT = Path(__file__).resolve().parent.parent
MS = ROOT / 'paper' / 'JRTIP-paper-v5.docx'
PKG = ROOT / 'submission-package' / 'manuscript' / 'JRTIP-paper-v5.docx'
DIFF = ROOT / 'paper' / 'polish-v5-diff.md'

E = []  # (¶index, 改动理由, old, new)

E.append((3, '摘要：去掉 "Three things make..." 的清单腔和 "interestingly"/"honestly delimits" 两处 AI 味副词，节奏更接近人写的摘要',
"Automated monitoring of group-housed pigs needs detectors that are accurate on rare, welfare-relevant behaviors and fast enough for low-cost edge hardware. We built a real-time multi-behavior detection framework on YOLOv11n and validated it on a Jetson Nano. Three things make the framework practical. First, a class-imbalance-aware sampling strategy based on frequency-capped offline oversampling improves rare-class detection without touching the network: the average precision of the low-frequency behavior active rises from 0.526 to 0.639 on the test set, and overall recall improves by 2.1 points on the validation set. Second, a FasterNet backbone substitution, combined with an identity-preserving integration strategy that transfers pre-trained weights by index-aligned remapping, cuts parameters by 4.4% while accuracy stays statistically comparable to the baseline across three repeated runs (test mean average precision at IoU 0.5 (mAP50) of 0.590 ± 0.009 vs. a three-seed baseline of 0.606 ± 0.008); interestingly, it is also the fastest of all models we benchmarked (117.6 frames per second (FPS) on an RTX 3090). Third, on-device validation on the Nano shows real-time operation (19.7 FPS at 640×640; 33.3 FPS at 480×480) at roughly 5 W total power. We also report a two-level generalization analysis—an unseen-sequence stress test and an independent farm dataset—that honestly delimits where the framework works and where it does not.",
"Automated monitoring of group-housed pigs calls for detectors that are accurate on rare, welfare-relevant behaviors yet fast enough for low-cost edge hardware. We built a real-time multi-behavior detection framework on YOLOv11n and validated it on a Jetson Nano, and three design choices carry the result. First, a class-imbalance-aware sampling strategy based on frequency-capped offline oversampling improves rare-class detection without touching the network: the average precision of the low-frequency behavior active rises from 0.526 to 0.639 on the test set, and overall recall improves by 2.1 points on the validation set. Second, a FasterNet backbone substitution—paired with an identity-preserving integration strategy that transfers pre-trained weights by index-aligned remapping—cuts parameters by 4.4% while keeping accuracy statistically comparable to the baseline across three repeated runs (test mean average precision at IoU 0.5 (mAP50) of 0.590 ± 0.009 vs. a three-seed baseline of 0.606 ± 0.008); it is also, unexpectedly, the fastest model we benchmarked (117.6 frames per second (FPS) on an RTX 3090). Third, on-device validation on the Nano confirms real-time operation (19.7 FPS at 640×640; 33.3 FPS at 480×480) at roughly 5 W total power. A two-level generalization analysis—an unseen-sequence stress test and an independent farm dataset—closes the loop by marking out where the framework works and where it does not."))

E.append((7, '引言：收掉 "This is why..." 的教科书腔，结尾改主动句式',
"For such monitoring to be economically viable, however, detection has to run on inexpensive edge devices inside the barn. A commercial farm may operate hundreds of pens; streaming all of that video to a cloud server is impractical over rural networks, and the recurring cost of cloud inference dwarfs the one-time cost of an edge board. Latency matters as well: an alert about a fight that arrives minutes late is of little use. This is why the dominant engineering trend is to bring the detector to the data, not the other way around.",
"For such monitoring to pay off, detection has to run on inexpensive edge devices inside the barn. A commercial farm may operate hundreds of pens; streaming all of that video to a cloud server is impractical over rural networks, and the recurring cost of cloud inference dwarfs the one-time cost of an edge board. Latency matters too: an alert about a fight that arrives minutes late is of little use. The engineering trend therefore runs in one direction—bring the detector to the data, not the other way around."))

E.append((15, '相关工作：尾句插入语节奏别扭（双逗号插入），改破折号 + "neither study" 明确主语',
"YOLO-based detectors have been applied to pig detection, individual tracking, posture recognition, and behavior analysis. For group-housed pigs, Tu et al. [5] combined YOLOv5s/YOLOX-S detectors with an improved DeepSORT tracker to track individual behaviors such as lying, feeding, and standing; Li et al. [6] paired YOLOX with the SCTS-SlowFast spatio-temporal module for joint detection and recognition of multiple behaviors; and more recent work proposed improved YOLOv8n and YOLOv11 variants—typically by inserting attention modules or re-designing feature-fusion paths—for standing, lying, feeding, drinking, and biting behaviors. Earlier, Alameer et al. [7] had already recognized postures and drinking behaviour for compromised-health monitoring from overhead barn footage. These works establish feasibility, but they largely assume server-side inference and balanced class distributions, and few report per-class results on rare behaviors. Two very recent studies push the same deployment agenda with different emphases. PBR-YOLO [27] combines a GhostNet backbone, a FasterNet block with efficient multi-scale attention, and a lightweight multi-path head for eight piglet behaviors, reporting 15.8 ms per frame with TensorRT on a Jetson Orin NX—an attention-augmented design demonstrated on a board far more powerful than the Nano-class hardware we target. Rahman et al. [28] trim YOLO11n for the single posture–nursing task in farrowing crates (removing the small-object detection head) and accelerate it with TensorRT, evaluating on a random image-level split that they explicitly frame as within-facility performance. Class-imbalance mitigation, central to our setting, is not part of either formulation and, to our knowledge, neither reports per-class accuracy on rare behaviors or generalization to unseen sequences.",
"YOLO-based detectors have been applied to pig detection, individual tracking, posture recognition, and behavior analysis. For group-housed pigs, Tu et al. [5] combined YOLOv5s/YOLOX-S detectors with an improved DeepSORT tracker to track individual behaviors such as lying, feeding, and standing; Li et al. [6] paired YOLOX with the SCTS-SlowFast spatio-temporal module for joint detection and recognition of multiple behaviors; and more recent work proposed improved YOLOv8n and YOLOv11 variants—typically by inserting attention modules or re-designing feature-fusion paths—for standing, lying, feeding, drinking, and biting behaviors. Earlier, Alameer et al. [7] had already recognized postures and drinking behaviour for compromised-health monitoring from overhead barn footage. These works establish feasibility, but they largely assume server-side inference and balanced class distributions, and few report per-class results on rare behaviors. Two very recent studies push the same deployment agenda with different emphases. PBR-YOLO [27] combines a GhostNet backbone, a FasterNet block with efficient multi-scale attention, and a lightweight multi-path head for eight piglet behaviors, reporting 15.8 ms per frame with TensorRT on a Jetson Orin NX—an attention-augmented design demonstrated on a board far more powerful than the Nano-class hardware we target. Rahman et al. [28] trim YOLO11n for the single posture–nursing task in farrowing crates (removing the small-object detection head) and accelerate it with TensorRT, evaluating on a random image-level split that they explicitly frame as within-facility performance. Class-imbalance mitigation—central to our setting—is absent from both formulations and, to our knowledge, neither study reports per-class accuracy on rare behaviors or generalization to unseen sequences."))

E.append((19, '相关工作："Still, ... seldom" 换 "Yet ... almost never"，避免与上段 Still 重复且更口语化',
"Relevant lightweight designs include depthwise-separable convolution (MobileNet [14]), feature-reuse convolution (GhostNet [15]), and partial convolution (FasterNet [16]), which performs spatial convolution on only a subset of channels to cut redundant memory access. Several agricultural studies deploy YOLO variants on Jetson-series boards with TensorRT acceleration and report encouraging frame rates [17, 18]. Still, on-device measurements remain rare in livestock behavior work, and two hardware facts are seldom discussed: Maxwell-generation boards such as the Jetson Nano have no native INT8 support, and TensorRT operator fusion can mask the theoretical advantages of lightweight operators at small model scales. We document both explicitly in Section 5. FasterNet-based substitution is itself established—Guo et al. [31] integrated FasterNet into YOLOv8 for real-time underwater detection and YOLO-FGD [32] applied the same idea to PCB inspection, both in this journal—so our contribution is not the substitution but the condition under which it preserves accuracy: identity-preserving weight transfer (Section 3.5), which these works do not discuss. A complementary route to lightness is post-training compression: Luo et al. [33] combine channel pruning with knowledge distillation for piglet behavior recognition, accepting a small accuracy margin in exchange for large parameter cuts without changing the training-time architecture.",
"Relevant lightweight designs include depthwise-separable convolution (MobileNet [14]), feature-reuse convolution (GhostNet [15]), and partial convolution (FasterNet [16]), which performs spatial convolution on only a subset of channels to cut redundant memory access. Several agricultural studies deploy YOLO variants on Jetson-series boards with TensorRT acceleration and report encouraging frame rates [17, 18]. Yet on-device measurements remain rare in livestock behavior work, and two hardware facts are almost never discussed: Maxwell-generation boards such as the Jetson Nano have no native INT8 support, and TensorRT operator fusion can mask the theoretical advantages of lightweight operators at small model scales. We document both explicitly in Section 5. FasterNet-based substitution is itself established—Guo et al. [31] integrated FasterNet into YOLOv8 for real-time underwater detection and YOLO-FGD [32] applied the same idea to PCB inspection, both in this journal—so our contribution is not the substitution but the condition under which it preserves accuracy: identity-preserving weight transfer (Section 3.5), which these works do not discuss. A complementary route to lightness is post-training compression: Luo et al. [33] combine channel pruning with knowledge distillation for piglet behavior recognition, accepting a small accuracy margin in exchange for large parameter cuts without changing the training-time architecture."))

E.append((45, '消融："retrospectively justifies" 拗口，改 "retroactively supports"；并删冗余词',
"Table 3 walks through the design space in the order we actually explored it, including the failures. Two attention-integration attempts (M1, M2) are listed first: both degrade accuracy noticeably, and their diagnosis (Section 3.5) is what pushed us toward identity-preserving integration in the first place. The FasterNet substitution alone (M3) costs 2.7 test points at 4.4% fewer parameters; a warm-restart continuation experiment (100 + 100 epochs, lr0 = 0.002) recovered 2.95 points, confirming that the gap is partly an under-training artifact of the substituted blocks rather than a capacity ceiling. The sampling strategy alone (M4) is the single most effective modification: test mAP50 rises from 0.5964 to 0.6035 and validation recall from 0.605 to 0.626 (+2.1 points, validation set), with the largest gains on rare classes (Section 4.4; training dynamics in Fig. 3). The combined model (M5) lands at 0.5932—within 0.32 points of the baseline—while carrying 4.4% fewer parameters, and it is the model we deploy in Section 5. Finally, the negative control (M6) applies the same sampling strategy to YOLOv12n: accuracy drops from 0.6135 to 0.5994 (−1.4 points), i.e., the benefit of exposure re-balancing does not transfer to the attention-centric base. We read this as evidence that YOLOv12n is natively more robust to imbalance and that re-sampling pushes it toward over-fitting; it also retrospectively justifies our empirical choice of YOLOv11n as the base model for this dataset-and-method combination.",
"Table 3 walks through the design space in the order we actually explored it, including the failures. Two attention-integration attempts (M1, M2) are listed first: both degrade accuracy noticeably, and their diagnosis (Section 3.5) is what pushed us toward identity-preserving integration in the first place. The FasterNet substitution alone (M3) costs 2.7 test points at 4.4% fewer parameters; a warm-restart continuation experiment (100 + 100 epochs, lr0 = 0.002) recovered 2.95 points, confirming that the gap is partly an under-training artifact of the substituted blocks rather than a capacity ceiling. The sampling strategy alone (M4) is the single most effective modification: test mAP50 rises from 0.5964 to 0.6035 and validation recall from 0.605 to 0.626 (+2.1 points, validation set), with the largest gains on rare classes (Section 4.4; training dynamics in Fig. 3). The combined model (M5) lands at 0.5932—within 0.32 points of the baseline—while carrying 4.4% fewer parameters, and it is the model we deploy in Section 5. Finally, the negative control (M6) applies the same sampling strategy to YOLOv12n: accuracy drops from 0.6135 to 0.5994 (−1.4 points), i.e., the benefit of exposure re-balancing does not transfer to the attention-centric base. We read this as evidence that YOLOv12n is natively more robust to imbalance and that re-sampling pushes it toward over-fitting; it also retroactively supports our empirical choice of YOLOv11n as the base for this dataset-and-method combination."))

E.append((50, '对比："are worth noting" 是典型 AI 套话，改 "stand out"',
"Table 4 places the two adopted variants against the comparison set under identical training conditions. M4 (0.6035) outperforms YOLOv5n (0.6001), RT-DETR-l (0.6008), YOLOv8n (0.5877), and the unmodified YOLOv11n baseline (0.5964), ranking second only to YOLOv12n (0.6135). M5 reaches 0.5932 at 2.47M parameters: it exceeds YOLOv8n while being 18% smaller, and it approaches RT-DETR-l at roughly one-thirteenth of the parameters and one-sixteenth of the FLOPs—a relevant operating point when the target hardware is a 5-watt edge board rather than a server GPU. Two observations are worth noting. First, YOLOv8n scores above our baseline on the validation split but below it on the test split, a reminder that validation rankings do not always survive contact with held-out data. Second, although YOLOv12n is the accuracy leader on this dataset, it is also the slowest model we benchmarked (Section 4.6), and—as M6 shows—it does not benefit from our sampling strategy; for an edge-oriented framework, we therefore regard it as a strong server-side reference rather than a deployment candidate.",
"Table 4 places the two adopted variants against the comparison set under identical training conditions. M4 (0.6035) outperforms YOLOv5n (0.6001), RT-DETR-l (0.6008), YOLOv8n (0.5877), and the unmodified YOLOv11n baseline (0.5964), ranking second only to YOLOv12n (0.6135). M5 reaches 0.5932 at 2.47M parameters: it exceeds YOLOv8n while being 18% smaller, and it approaches RT-DETR-l at roughly one-thirteenth of the parameters and one-sixteenth of the FLOPs—a relevant operating point when the target hardware is a 5-watt edge board rather than a server GPU. Two observations stand out. First, YOLOv8n scores above our baseline on the validation split but below it on the test split, a reminder that validation rankings do not always survive contact with held-out data. Second, although YOLOv12n is the accuracy leader on this dataset, it is also the slowest model we benchmarked (Section 4.6), and—as M6 shows—it does not benefit from our sampling strategy; for an edge-oriented framework, we therefore regard it as a strong server-side reference rather than a deployment candidate."))

E.append((55, '统计可靠性："would not survive a careful reviewer" 是在审稿人面前谈审稿，元话语过强且有防御感，改为对证据本身陈述',
"Single training runs of small detectors can easily fluctuate by half a point, so we repeated the baseline and the two adopted models with three different seeds. The baseline scores 0.5822 ± 0.0087 on validation and 0.6060 ± 0.0084 on test (seed 0 exactly reproduces the 0.5964 single run reported in Table 3). M4 scores 0.5790 ± 0.0054 on validation and 0.5987 ± 0.0062 on test; M5 scores 0.5620 ± 0.0079 and 0.5904 ± 0.0086, respectively. Against the three-seed baseline test mean, the M5 difference (−0.016) amounts to about two standard errors of the seed-to-seed variation and is not significant at the 0.05 level (two-sample t-test, p ≈ 0.09), so we report M5 as statistically comparable to the baseline rather than superior to it. The M4 test mean sits within one baseline standard deviation (−0.007)—its real value, shown in Section 4.4, is the redistribution of accuracy toward rare, welfare-relevant behaviors and the +2.1-point recall gain on validation, not a headline mAP increase. We deliberately present it this way: an overall-gain framing would not survive a careful reviewer, and the rare-class framing is both honest and, for welfare alerting, the practically relevant one.",
"Single training runs of small detectors can easily fluctuate by half a point, so we repeated the baseline and the two adopted models with three different seeds. The baseline scores 0.5822 ± 0.0087 on validation and 0.6060 ± 0.0084 on test (seed 0 exactly reproduces the 0.5964 single run reported in Table 3). M4 scores 0.5790 ± 0.0054 on validation and 0.5987 ± 0.0062 on test; M5 scores 0.5620 ± 0.0079 and 0.5904 ± 0.0086, respectively. Against the three-seed baseline test mean, the M5 difference (−0.016) amounts to about two standard errors of the seed-to-seed variation and is not significant at the 0.05 level (two-sample t-test, p ≈ 0.09), so we report M5 as statistically comparable to the baseline rather than superior to it. The M4 test mean sits within one baseline standard deviation (−0.007)—its real value, shown in Section 4.4, is the redistribution of accuracy toward rare, welfare-relevant behaviors and the +2.1-point recall gain on validation, not a headline mAP increase. We deliberately present it this way: an overall-gain framing would overstate the evidence, while the rare-class framing is both honest and, for welfare alerting, the practically relevant one."))

E.append((57, '效率："This is expected rather than contradictory" 与前句断开更顺，合并为破折号收束',
"Table 5 reports efficiency on the RTX 3090 (FP32, batch 1, 640×640). M5 is the fastest model in the entire comparison at 117.6 FPS (Fig. 4)—ahead of the baseline (112.8) and M4 (112.1), and 50% ahead of YOLOv12n (78.4). One boundary should be stated plainly: the efficiency gain shows up in parameter count (−4.4%) and measured speed, not in FLOPs, which stay essentially flat (6.3G → 6.5G). This is expected rather than contradictory. FLOPs count arithmetic operations, while partial convolution mainly cuts redundant memory access; latency benchmarks capture the latter, the FLOPs counter does not. The same caveat will reappear, in amplified form, on the Jetson Nano (Section 5), where TensorRT operator fusion absorbs most of the remaining difference.",
"Table 5 reports efficiency on the RTX 3090 (FP32, batch 1, 640×640). M5 is the fastest model in the entire comparison at 117.6 FPS (Fig. 4)—ahead of the baseline (112.8) and M4 (112.1), and 50% ahead of YOLOv12n (78.4). One boundary deserves to be stated plainly: the efficiency gain shows up in parameter count (−4.4%) and measured speed, not in FLOPs, which stay essentially flat (6.3G → 6.5G). This is expected, not contradictory. FLOPs count arithmetic operations, while partial convolution mainly cuts redundant memory access; latency benchmarks capture the latter, the FLOPs counter does not. The same caveat will reappear, in amplified form, on the Jetson Nano (Section 5), where TensorRT operator fusion absorbs most of the remaining difference."))

E.append((71, '部署：首句被动改主动（"We report"），"each cost us" 补 "one"',
"Three practical findings from the deployment work are reported because they are rarely documented in this literature and each cost us real time. First, INT8 quantization is effectively unavailable on this board: the Maxwell GPU has no native INT8 units and TensorRT 8.2 calibration fails on it, so FP16 is the practical precision floor for Nano-class hardware; buyers of new hardware should budget for an Orin-class board if INT8 is needed. Second, the on-device latency difference between M5 and the baseline is under 2%—TensorRT operator fusion absorbs the partial-convolution advantage at this model scale, so the server-side speed gap (Table 5) does not carry over to the edge. The honest claim is therefore parity on the Nano with a smaller model, not a speed win. Third, the build toolchain is fragile in ways worth knowing before fieldwork: an interrupted onnxslim simplification left a silently corrupted ONNX file that only surfaced at engine-build time, and a subsequent run of build failures reported misleading cuDNN symbol errors that a reboot cleared (stale GPU state from the crashed build). Exporting without graph simplification and running one engine build at a time, with a reboot after any crashed build, made the pipeline reproducible. None of these issues appear in server-side evaluations, which is precisely why we report them here.",
"We report three practical findings from the deployment work because they are rarely documented in this literature and each one cost us real time. First, INT8 quantization is effectively unavailable on this board: the Maxwell GPU has no native INT8 units and TensorRT 8.2 calibration fails on it, so FP16 is the practical precision floor for Nano-class hardware; buyers of new hardware should budget for an Orin-class board if INT8 is needed. Second, the on-device latency difference between M5 and the baseline is under 2%—TensorRT operator fusion absorbs the partial-convolution advantage at this model scale, so the server-side speed gap (Table 5) does not carry over to the edge. The honest claim is therefore parity on the Nano with a smaller model, not a speed win. Third, the build toolchain is fragile in ways worth knowing before fieldwork: an interrupted onnxslim simplification left a silently corrupted ONNX file that only surfaced at engine-build time, and a subsequent run of build failures reported misleading cuDNN symbol errors that a reboot cleared (stale GPU state from the crashed build). Exporting without graph simplification and running one engine build at a time, with a reboot after any crashed build, made the pipeline reproducible. None of these issues appear in server-side evaluations, which is precisely why we report them here."))

E.append((86, '结论："delineates ... honestly" 的 honestly 是 AI 味修饰；末句 today/tomorrow 对仗保留但改更自然的并列',
"This paper presented a lightweight, real-time multi-behavior detection framework for group-housed pigs that combines class-imbalance-aware sampling with a FasterNet backbone substitution under an identity-preserving integration strategy. On a public ten-class dataset, the framework lifts the average precision of the low-frequency behavior active by 11.3 points on the held-out test set and validation recall by 2.1 points, keeps overall accuracy statistically comparable to the YOLOv11n baseline across three repeated runs, reduces parameters by 4.4%, and is the fastest of all benchmarked detectors on the server GPU (117.6 FPS). On-device validation on a Jetson Nano confirms real-time operation (19.7 FPS at 640×640; 33.3 FPS at 480×480) at approximately 5 W. A two-level generalization analysis—an unseen-sequence stress test and zero-shot evaluation on an independent farm dataset—delineates the operating envelope honestly: the framework is ready for same-farm deployment today, and it identifies domain adaptation and multi-farm data collection as the key directions for cross-farm operation tomorrow.",
"This paper presented a lightweight, real-time multi-behavior detection framework for group-housed pigs that combines class-imbalance-aware sampling with a FasterNet backbone substitution under an identity-preserving integration strategy. On a public ten-class dataset, the framework lifts the average precision of the low-frequency behavior active by 11.3 points on the held-out test set and validation recall by 2.1 points, keeps overall accuracy statistically comparable to the YOLOv11n baseline across three repeated runs, reduces parameters by 4.4%, and is the fastest of all benchmarked detectors on the server GPU (117.6 FPS). On-device validation on a Jetson Nano confirms real-time operation (19.7 FPS at 640×640; 33.3 FPS at 480×480) at approximately 5 W. A two-level generalization analysis—an unseen-sequence stress test and zero-shot evaluation on an independent farm dataset—maps the operating envelope without embellishment: the framework is ready for same-farm deployment today, with domain adaptation and multi-farm data collection as the key directions for cross-farm operation tomorrow."))

NUM_TOKEN = re.compile(r'\S*\d\S*')
REF_TOKEN = re.compile(r'(Fig\.\s*\d+[ab]?|Table\s+[A-Z]?\d+|Section\s+\d+(?:\.\d+)?|\[[\d,\s\-–]+\])')

def freeze_check(old, new, idx):
    a = Counter(NUM_TOKEN.findall(old))
    b = Counter(NUM_TOKEN.findall(new))
    assert a == b, f'¶{idx} 数字 token 漂移: {a - b} / {b - a}'
    a2 = Counter(REF_TOKEN.findall(old))
    b2 = Counter(REF_TOKEN.findall(new))
    assert a2 == b2, f'¶{idx} 引用漂移: {a2 - b2} / {b2 - a2}'

def main():
    doc = Document(str(MS))
    lines = ['# 英文 v5 人味化润色 · 逐段对照清单', '',
             '说明：只动句式和衔接，全部数字、引用 [n]、图表号经脚本多重集校验零漂移。',
             '其余 80+ 段经通读判定已是自然人学术体，刻意不动（过度改写反而引入机器味）。', '']
    for idx, reason, old, new in E:
        p = doc.paragraphs[idx]
        assert p.text.strip() == old.strip(), f'¶{idx} 原文不匹配:\n{p.text[:120]}'
        freeze_check(old, new, idx)
        for r in p.runs[1:]:
            r.text = ''
        p.runs[0].text = new
        lines += [f'## ¶{idx} — {reason}', '',
                  '**改前**', f'> {old}', '',
                  '**改后**', f'> {new}', '', '---', '']
        print(f'¶{idx} OK')
    doc.save(str(MS))
    shutil.copy(str(MS), str(PKG))
    DIFF.write_text('\n'.join(lines), encoding='utf-8')
    print(f'saved + package refreshed + diff -> {DIFF}')

if __name__ == '__main__':
    main()
